version: "3.3"

services:
  localstack:
    image: localstack/localstack
    network_mode: "host"
    container_name: localstack
    environment:
      - "SERVICES=${LOCALSTACK_SERVICES:-kinesis}"
      - "DEFAULT_REGION=${AWS_REGION:-us-east-1}"
      - "HOSTNAME=${LOCALSTACK_HOSTNAME:-localhost}"
      - "KINESIS_ERROR_PROBABILITY=${LOCALSTACK_KINESIS_ERROR_PROBABILITY:-0.0}"
      - "DATA_DIR=${LOCALSTACK_DATA_DIR:-/tmp/localstack/data}"
